In [71]:
import numpy as np
e = 1.0E-4  
counter = 0

In [72]:
# Matrix should be positively defined (sylvester criterion)

d_file = 'data.txt'
with open(d_file,'r') as file:
    matrix_height = int(file.readline( ))
    A = np.matrix([list(map(float, file.readline().split()))
                       for i in range(matrix_height)]) 
    b = np.matrix(list(map(float, file.readline().split()))).transpose() 
    x = np.matrix(list(map(float, file.readline().split()))).transpose()

In [73]:
def min_residue(A, b, x):
    r = A * x - b  # vector of residue
    t = np.dot((A * r).transpose(), r) / (np.linalg.norm(A * r)**2) # tau
    x = x - float(t) * r  # new solution of SLAE
    return (A, b, x)

In [74]:
print('min residue method\n')
print('Matrix A:\n', A)
print('Vector B: ', b.transpose())
print('Vector of approximations', x.transpose(), end='\n\n')


min residue method

Matrix A:
 [[20.9  1.2  0.7]
 [ 1.2 21.2  1.5]
 [ 0.9  2.5 19.8]]
Vector B:  [[21.7  27.46 28.76]]
Vector of approximations [[0. 0. 0.]]



In [75]:
print('Step', 'Solution vector', sep='\t\t')
while np.linalg.norm(A*x - b) > e:  
    print(counter, x.transpose(), sep='\t\t')
    A, b, x = min_residue(A, b, x)
    counter += 1

print('\nVector with precision ',
                                e, ': ', x.transpose())
print('Iterations: ', counter)


Step		Solution vector
0		[[0. 0. 0.]]
1		[[0.93149704 1.17875155 1.23455552]]
2		[[0.92896963 1.15189719 1.2630998 ]]
3		[[0.9297508  1.15320861 1.26460306]]
4		[[0.92970599 1.15317604 1.26465814]]

Vector with precision  0.0001 :  [[0.92970925 1.15317754 1.26466232]]
Iterations:  5


In [76]:
np.linalg.solve(A,b)

matrix([[0.92970927],
        [1.15317712],
        [1.26466257]])